version: "3.3"

volumes:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: ../backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    env_file: ../backend/.env
    depends_on:
      - db
  frontend:
    ports:
      - "8080:8080"
    build:
      context: ../frontend/
      dockerfile: Dockerfile.local
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
